GET http://127.0.0.1:8080/hello?key=value


###


POST http://127.0.0.1:8080/hello

{"hello":"world"}

###

GET http://127.0.0.1:8080/
Accept: */*

<> 2019-07-01T012238.200.html

###


GET http://127.0.0.1:8080/hello
Authorization: xlwliaiffkasdff

{"hello":"world"}

###

